### ISSUE TITLE
리뷰 수정 api 로직 오류 해결

### ISSUE THREAD

**Issue by luke0408** [BETTER-iTER/Server#195]
## 설명
> 로직상 문제 해결

## To-do
- [ ] api 수정

**Comment by luke0408** [comment]
# 에러 상황

- 발생 : updateReviewImages -> reviewImageRepository.save()
- 내용 : JDBC transaction marked for rollback-only (exception provided for stack trace)
  - transaction commit이 실패해 발생하는 에러

```
java.lang.Exception: exception just for purpose of providing stack trace
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.markRollbackOnly(JdbcResourceLocalTransactionCoordinatorImpl.java:324) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.markRollbackOnly(TransactionImpl.java:203) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.setRollbackOnly(TransactionImpl.java:224) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.springframework.orm.jpa.JpaTransactionManager$JpaTransactionObject.setRollbackOnly(JpaTransactionManager.java:712) ~[spring-orm-5.3.29.jar:5.3.29]
	at org.springframework.orm.jpa.JpaTransactionManager.doSetRollbackOnly(JpaTransactionManager.java:611) ~[spring-orm-5.3.29.jar:5.3.29]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processRollback(AbstractPlatformTransactionManager.java:844) ~[spring-tx-5.3.29.jar:5.3.29]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.rollback(AbstractPlatformTransactionManager.java:809) ~[spring-tx-5.3.29.jar:5.3.29]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.completeTransactionAfterThrowing(TransactionAspectSupport.java:672) ~[spring-tx-5.3.29.jar:5.3.29]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392) ~[spring-tx-5.3.29.jar:5.3.29]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.29.jar:5.3.29]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.29.jar:5.3.29]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.29.jar:5.3.29]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.29.jar:5.3.29]
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:174) ~[spring-data-jpa-2.7.15.jar:2.7.15]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.29.jar:5.3.29]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.29.jar:5.3.29]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.29.jar:5.3.29]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:241) ~[spring-aop-5.3.29.jar:5.3.29]
	at jdk.proxy2/jdk.proxy2.$Proxy169.save(Unknown Source) ~[na:na]
```

1. 프록시 메서드로 감싸진 save 메서드 호출
2. PersistenceExceptionTranslationInterceptor 동작
3. 트랜젝션을 가지고 invokeWithinTransaction 호출
4. completeTransactionAfterThrowing 호출
5. JpaTransactionManager 에서 JpaTransactionObject.setRollbackOnly
6. 그에 따라 TransactionDriverControlImpl.markRollbackOnly 이 호출 되어 에러 발생

**Comment by luke0408** [comment]
# Logging Level 조정 후 에러 문구

- 에러레벨
```yaml
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    root: info
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm: TRACE
    org.springframework.transaction: TRACE
    com.zaxxer.hikari: TRACE
    com.mysql.cj.jdbc: TRACE
```

- 에러문구
- 참고: https://techblog.woowahan.com/2606/
```
2024-03-07 03:59:44.474 TRACE 18085 --- [nio-8080-exec-2] o.s.t.i.TransactionInterceptor           : Completing transaction for [org.springframework.data.jpa.repository.support.SimpleJpaRepository.save] after exception: javax.persistence.PersistenceException: org.hibernate.HibernateException: The database returned no natively generated identity value
2024-03-07 03:59:44.474 DEBUG 18085 --- [nio-8080-exec-2] o.s.orm.jpa.JpaTransactionManager        : Participating transaction failed - marking existing transaction as rollback-only
2024-03-07 03:59:44.474 DEBUG 18085 --- [nio-8080-exec-2] o.s.orm.jpa.JpaTransactionManager        : Setting JPA transaction on EntityManager [SessionImpl(1706161935<open>)] rollback-only
2024-03-07 03:59:44.475 TRACE 18085 --- [nio-8080-exec-2] o.s.t.i.TransactionInterceptor           : Completing transaction for [com.example.betteriter.fo_domain.review.service.ReviewService.updateReview] after exception: org.springframework.orm.jpa.JpaSystemException: The database returned no natively generated identity value; nested exception is org.hibernate.HibernateException: The database returned no natively generated identity value
2024-03-07 03:59:44.475 DEBUG 18085 --- [nio-8080-exec-2] o.s.orm.jpa.JpaTransactionManager        : Initiating transaction rollback
2024-03-07 03:59:44.475 DEBUG 18085 --- [nio-8080-exec-2] o.s.orm.jpa.JpaTransactionManager        : Rolling back JPA transaction on EntityManager [SessionImpl(1706161935<open>)]
2024-03-07 03:59:44.477 DEBUG 18085 --- [nio-8080-exec-2] o.s.orm.jpa.JpaTransactionManager        : Not closing pre-bound JPA EntityManager after transaction
2024-03-07 03:59:44.488 DEBUG 18085 --- [nio-8080-exec-2] o.j.s.OpenEntityManagerInViewInterceptor : Closing JPA EntityManager in OpenEntityManagerInViewInterceptor
```

`org.hibernate.HibernateException: The database returned no natively generated identity value`
- DataBase 설정 에러라고 함
- 참고: https://velog.io/@myway00/mysql-%EB%B0%B0%ED%8F%AC-%EC%97%90%EB%9F%AC-returned-no-natively-generated-identity-value
